"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Organisateur_1 = require("./Organisateur");
var Gestionnaire_1 = require("./Gestionnaire");
// let user2 = new Utilisateur('Oudo Kanté','oudo@gmail',65665689,'azerty');
// user2.CreerCompte();
// user2.Stock_userid('oudo@gmail');
// user2.RechercherEvent('Concert de Gaspi');
var gest1 = new Gestionnaire_1.Gestionnaire('Maliba Production', 'maliba@gmail.com', 'maliba');
// gest1.AjoutGestionnaire();
// gest1.AjoutLieu("Palais des Sports","Grande Salle","Bamako",1000);
var org2 = new Organisateur_1.Organisateur("Djageleya Music", "djageleya@gmail.com", "djagueleya");
// org2.AjouterEvent("Rap AfroTrap","payant","rap et tous","Palais des Sports");
org2.AjouterTypeevent("Payant");
// gest1.SupGestionnaire('maliba@gmail.com');
// gest1.ModifierGestionnaire('Dlageleya','maliba@gmail.com','maliba');
// gest1.AjoutOraganisateur('Bamada City','bamada@gmail.com','bamada');
